spring.application.name=codecanvas

spring.datasource.url=jdbc:mysql://localhost:3306/codecanvas_db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT config
jwt.secret=codecanvasSecretKeyForJWTSigningMustBeLongEnough123456789
jwt.expiration=86400000
gemini.api.key=YOUR_KEY_HERE_SET_LOCALLY
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent